#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------

buoyantPimpleFoam >& log & sleep 0.01; tail -f log

# Plotting output
export time=32400

for var in T U k nut; do
    writeCellDataxyz $var -time $time
    sort -g --key=3 $time/$var.xyz > $time/$var.dat
    gmtPlot plots/plot$var.gmt
done
