#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh
#runApplication setFields
rm -rf [0-9]*
cp -r init_0 0
runApplication setTheta
rm 0/thetaf 0/BruntFreq2f
runApplication setHydroStaticPressure
# Fix the top boundary conditions
sed -i 's/fixedValue/hydrostatic_p_rgh;\n        gradient uniform 0/g' 0/p_rgh

runApplication $application

#------------------------------------------------------------------------------

buoyantPimpleFoam >& log & sleep 0.01; tail -f log

# Plotting output
export time=32400

for var in theta T U k nut; do
    writeCellDataxyz $var -time $time
    sort -g --key=3 $time/$var.xyz > $time/$var.dat
    gmtPlot plots/plot$var.gmt
done

