#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------

buoyantPimpleFoam >& log & sleep 0.01; tail -f log
time=100
gmtFoam -time $time UT
gv $time/UT.pdf &

